---
title: "University Intake Analysis"
author: "Your Name"
format:
  typst:
    toc: true
    keep-typ: true
    include-in-header:
      - file: typst-functions.typ
---



+ My-report
1. report.qmd
2. typst-functions.typ
3. task-data.typ
4. task-analysis.typ

# Introduction

This report examines programme intake across campuses and academic
years.

# Data preparation

The following task describes the required data-preparation work.

```{=typst}
#include "task-data.typ"
```

```{=typst}
#include "task-analysis.typ"
```


```{r}
#| echo: true
library(tidyverse)
# Your R analysis
mtcars %>%  head(5) %>%  knitr::kable(format = "pipe")
```


```{r}
#include: false
#| echo: true
library(dplyr)
avgMPG <- mtcars %>% summarise(avg_mpg = mean(mpg))

bestCar <- mtcars %>% filter(mpg == max(mpg)) %>% rownames_to_column(var='car')  %>% select(car, mpg)

typst_content <- c(  '#import "typst-functions.typ": task-box',  "",  sprintf( '#task-box([Result generated by R])[Average MPG: *%.1f*. Highest-MPG car: *%s*.]',    avgMPG,  bestCar  ))

writeLines(typst_content, "generated-result.typ")
```

The following Typst content was generated by the preceding R calculation:

```{=typst}
#include "generated-result.typ"
```


```{r}
#| include: false

png("mtcars-plot.png", width = 1000, height = 650, res = 130)
plot(  mtcars$wt,  mtcars$mpg,  pch = 19,  col = "steelblue",  xlab = "Weight",  ylab = "Miles per gallon")

dev.off()
```

```{=typst}
#figure(
  image("mtcars-plot.png", width: 80%),
  caption: [Relationship between vehicle weight and fuel efficiency],
)
```